# Generated by Django 2.1.5 on 2019-02-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyluv_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
