# Generated by Django 2.1.5 on 2019-02-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('documentation', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
