# Generated by Django 2.1.5 on 2019-02-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyluv_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
