# Generated by Django 2.1.5 on 2019-02-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyluv_api', '0002_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='api',
            name='url',
        ),
        migrations.AlterField(
            model_name='api',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyluv_home.User'),
        ),
        migrations.AddField(
            model_name='apiurl',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyluv_api.API'),
        ),
    ]
