# Generated by Django 2.1.5 on 2019-02-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyluv_api', '0003_auto_20190210_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiurl',
            old_name='author',
            new_name='base_api',
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='base_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyluv_api.API'),
        ),
    ]
