# Generated by Django 2.1.5 on 2019-02-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyluv_api', '0004_auto_20190210_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='base_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='apiurl',
            name='base_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyluv_api.API'),
        ),
    ]
